# Generated by Django 5.2.3 on 2025-06-12 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_assigned_at_volunteerprofile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='candidate',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.volunteer'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
