# Generated by Django 5.2.3 on 2025-06-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_created_at_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
