# Generated by Django 5.2.3 on 2025-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_candidate_deleted_alter_candidate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('speaker_name', models.CharField(max_length=255)),
                ('candidates_followed_up', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='followed_up',
            field=models.BooleanField(default=False),
        ),
    ]
