# Generated by Django 5.2.3 on 2025-06-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_followupsession_candidate_followed_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
