# Generated by Django 5.2.3 on 2025-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_candidate_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceResetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset_date', models.DateField()),
            ],
        ),
    ]
