# Generated by Django 5.2.3 on 2025-06-12 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attendanceresettracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
