# Generated by Django 5.2.3 on 2025-06-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
