# Generated by Django 5.2.3 on 2025-06-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_candidate_address_candidate_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='mother_tongue',
        ),
    ]
