# Generated by Django 5.2.3 on 2025-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_comment_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
