# Generated by Django 5.2.3 on 2025-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_candidate_mother_tongue'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='follow_up_status',
            field=models.CharField(blank=True, choices=[('Coming', 'Coming'), ('Out of Station', 'Out of Station'), ('Busy', 'Busy'), ('Not Feeling Well', 'Not Feeling Well'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='follow_up_status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
