# Generated by Django 5.2.3 on 2025-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_candidate_follow_up_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceresettracker',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followupsession',
            name='candidates_attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='followupsession',
            name='candidates_newly_registered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='followupsession',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
