# Generated by Django 5.2.3 on 2025-06-17 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_attendanceresettracker_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='attendanceresettracker',
            options={'verbose_name': 'Attendance Reset Tracker'},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='followupsession',
            name='followed_up_but_not_attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('volunteer', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('candidate', 'date')},
        ),
    ]
