# Generated by Django 5.2.3 on 2025-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_assignment_options_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupsession',
            name='candidates_attended',
        ),
        migrations.RemoveField(
            model_name='followupsession',
            name='candidates_followed_up',
        ),
        migrations.RemoveField(
            model_name='followupsession',
            name='candidates_newly_registered',
        ),
        migrations.RemoveField(
            model_name='followupsession',
            name='followed_up_but_not_attended',
        ),
        migrations.AddField(
            model_name='followupsession',
            name='attended_candidates',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to='core.candidate'),
        ),
        migrations.AddField(
            model_name='followupsession',
            name='followed_up_candidates',
            field=models.ManyToManyField(blank=True, related_name='followed_sessions', to='core.candidate'),
        ),
        migrations.AddField(
            model_name='followupsession',
            name='new_candidates',
            field=models.ManyToManyField(blank=True, related_name='new_sessions', to='core.candidate'),
        ),
        migrations.AddField(
            model_name='followupsession',
            name='not_attended_candidates',
            field=models.ManyToManyField(blank=True, related_name='not_attended_sessions', to='core.candidate'),
        ),
        migrations.AlterField(
            model_name='followupsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='followupsession',
            name='speaker_name',
            field=models.CharField(max_length=100),
        ),
    ]
