# Generated by Django 5.2.3 on 2025-06-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_followupsession_candidates_attended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupsession',
            old_name='attended_candidates',
            new_name='attended',
        ),
        migrations.RenameField(
            model_name='followupsession',
            old_name='new_candidates',
            new_name='new',
        ),
        migrations.RenameField(
            model_name='followupsession',
            old_name='not_attended_candidates',
            new_name='not_attended',
        ),
        migrations.RemoveField(
            model_name='followupsession',
            name='followed_up_candidates',
        ),
        migrations.RemoveField(
            model_name='followupsession',
            name='speaker_name',
        ),
        migrations.AddField(
            model_name='followupsession',
            name='followed_up',
            field=models.ManyToManyField(blank=True, related_name='followed_up_sessions', to='core.candidate'),
        ),
    ]
