# Generated by Django 5.2.3 on 2025-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_attended_candidates_followupsession_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='level',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4')], max_length=2, null=True),
        ),
    ]
