# Generated by Django 5.2.3 on 2025-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_candidate_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='level',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4')], help_text="Select the candidate's skill or engagement level (L1–L4).", max_length=2, null=True),
        ),
    ]
