# Generated by Django 5.2.3 on 2025-06-18 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_candidatecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatecomment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='candidatecomment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='candidatecomment',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='candidatecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
