# Generated by Django 5.2.3 on 2025-06-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_attendance_options_attendance_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
