# Generated by Django 5.2.3 on 2025-06-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='follow_up_status',
            field=models.CharField(blank=True, choices=[('Coming', 'Coming'), ('Out of Station', 'Out of Station'), ('Busy', 'Busy'), ('Not Feeling Well', 'Not Feeling Well'), ('Not Reciving calls', 'Not Reciving calls'), ('Not Interested', 'Not Interested'), ('Trying to avoide', 'Trying to avoide'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
