# Generated by Django 5.2.3 on 2025-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_candidate_follow_up_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupsession',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
